# Generated by Django 4.2.1 on 2023-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=10)),
                ('TypeName', models.CharField(max_length=25)),
                ('CPU_Brand', models.CharField(max_length=25)),
                ('CPU_Frequency', models.FloatField(max_length=2)),
                ('OpSys', models.CharField(max_length=20)),
                ('RAM', models.PositiveSmallIntegerField(max_length=2)),
                ('GPU', models.CharField(max_length=6)),
                ('Memory_SSD', models.IntegerField(max_length=4)),
            ],
        ),
    ]
