# Generated by Django 4.2.1 on 2023-06-04 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_input_data_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='Price',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input_data',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 21, 27, 28, 339904)),
        ),
    ]
