# Generated by Django 4.2.1 on 2023-06-04 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_input_data_price_input_data_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='input_data',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 21, 35, 1, 539505)),
        ),
        migrations.AddField(
            model_name='input_data',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
