# Generated by Django 4.2.1 on 2023-06-04 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_input_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 21, 37, 4, 364978)),
        ),
    ]
